<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<c:set var="pageTitle" value="Report Drafts &amp; Publishing" scope="request"/>
<jsp:include page="../common/app-frame-start.jsp"/>

<c:if test="${not empty success}"><div class="alert alert-success py-2 mb-3">${success}</div></c:if>
<c:if test="${not empty error}"><div class="alert alert-danger py-2 mb-3">${error}</div></c:if>

<div class="sb-card mb-4">
    <h6 class="mb-3">Create a new report draft</h6>
    <form method="post" action="<c:url value='/reports/draft'/>" class="row g-3">
        <c:if test="${not empty _csrf}"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /></c:if>
        <div class="col-md-5">
            <label class="form-label">Report name</label>
            <input class="form-control" name="name" required>
        </div>
        <div class="col-md-4">
            <label class="form-label">Type</label>
            <input class="form-control" name="type" placeholder="e.g. MONTHLY_COMPLIANCE" required>
        </div>
        <div class="col-md-3">
            <label class="form-label">Params (optional)</label>
            <input class="form-control" name="params">
        </div>
        <div class="col-12"><button class="btn btn-primary">Save draft</button></div>
    </form>
</div>

<div class="sb-card">
    <h6 class="mb-3">All reports</h6>
    <div class="table-responsive">
        <table class="table align-middle">
            <thead><tr><th>Name</th><th>Type</th><th>Status</th><th>Generated By</th><th>Created</th><th></th></tr></thead>
            <tbody>
            <c:forEach var="r" items="${reports}">
                <tr>
                    <td><c:out value="${r.name}"/></td>
                    <td><c:out value="${r.type}"/></td>
                    <td><span class="badge bg-secondary"><c:out value="${r.status}"/></span></td>
                    <td><c:out value="${r.generatedBy.fullName}"/></td>
                    <td class="small"><c:out value="${r.createdAt}"/></td>
                    <td class="d-flex gap-1 flex-wrap">
                        <c:if test="${r.status == 'DRAFT' || r.status == 'REJECTED'}">
                            <form method="post" action="<c:url value='/reports/${r.id}/update'/>" class="d-flex gap-1">
                                <c:if test="${not empty _csrf}"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /></c:if>
                                <input class="form-control form-control-sm" name="name" value="<c:out value='${r.name}'/>" style="width:120px">
                                <input type="hidden" name="type" value="<c:out value='${r.type}'/>">
                                <button class="btn btn-sm btn-outline-secondary">Update</button>
                            </form>
                            <form method="post" action="<c:url value='/reports/${r.id}/submit-publish'/>">
                                <c:if test="${not empty _csrf}"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /></c:if>
                                <button class="btn btn-sm btn-primary">Submit for publish</button>
                            </form>
                            <sec:authorize access="hasAnyRole('BANK_MANAGER','SYSTEM_ADMINISTRATOR')">
                                <form method="post" action="<c:url value='/reports/${r.id}/publish'/>">
                                    <c:if test="${not empty _csrf}"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /></c:if>
                                    <button class="btn btn-sm btn-success">Publish</button>
                                </form>
                            </sec:authorize>
                            <form method="post" action="<c:url value='/reports/${r.id}/delete'/>"
                                  onsubmit="return confirm('Permanently delete this draft report?');">
                                <c:if test="${not empty _csrf}"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /></c:if>
                                <button class="btn btn-sm btn-danger">Delete Draft</button>
                            </form>
                        </c:if>
                        <c:if test="${r.status == 'PUBLISHED'}">
                            <form method="post" action="<c:url value='/reports/${r.id}/request-archive'/>">
                                <c:if test="${not empty _csrf}"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /></c:if>
                                <button class="btn btn-sm btn-outline-warning">Request archive</button>
                            </form>
                            <sec:authorize access="hasAnyRole('BANK_MANAGER','SYSTEM_ADMINISTRATOR')">
                                <form method="post" action="<c:url value='/reports/${r.id}/delete'/>"
                                      onsubmit="return confirm('Permanently delete this report from database?');">
                                    <c:if test="${not empty _csrf}"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /></c:if>
                                    <button class="btn btn-sm btn-outline-danger">Delete</button>
                                </form>
                            </sec:authorize>
                            <sec:authorize access="!hasAnyRole('BANK_MANAGER','SYSTEM_ADMINISTRATOR')">
                                <form method="post" action="<c:url value='/reports/${r.id}/request-delete'/>"
                                      onsubmit="return confirm('Request deletion of this report? Manager approval is required.');">
                                    <c:if test="${not empty _csrf}"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /></c:if>
                                    <button class="btn btn-sm btn-outline-danger">Request Delete</button>
                                </form>
                            </sec:authorize>
                        </c:if>
                        <c:if test="${r.status == 'PENDING_PUBLISH'}">
                            <span class="text-muted small align-self-center">Awaiting manager approval…</span>
                            <sec:authorize access="hasAnyRole('BANK_MANAGER','SYSTEM_ADMINISTRATOR')">
                                <form method="post" action="<c:url value='/reports/${r.id}/publish'/>">
                                    <c:if test="${not empty _csrf}"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /></c:if>
                                    <button class="btn btn-sm btn-success">Publish Now</button>
                                </form>
                                <form method="post" action="<c:url value='/reports/${r.id}/delete'/>"
                                      onsubmit="return confirm('Permanently delete this report from database?');">
                                    <c:if test="${not empty _csrf}"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /></c:if>
                                    <button class="btn btn-sm btn-outline-danger">Delete</button>
                                </form>
                            </sec:authorize>
                        </c:if>
                        <c:if test="${r.status == 'ARCHIVED'}">
                            <sec:authorize access="hasAnyRole('BANK_MANAGER','SYSTEM_ADMINISTRATOR')">
                                <form method="post" action="<c:url value='/reports/${r.id}/delete'/>"
                                      onsubmit="return confirm('Permanently delete this archived report?');">
                                    <c:if test="${not empty _csrf}"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /></c:if>
                                    <button class="btn btn-sm btn-outline-danger">Delete</button>
                                </form>
                            </sec:authorize>
                        </c:if>
                    </td>
                </tr>
            </c:forEach>
            <c:if test="${empty reports}"><tr><td colspan="6" class="text-muted text-center py-4">No reports yet.</td></tr></c:if>
            </tbody>
        </table>
    </div>
</div>

<jsp:include page="../common/app-frame-end.jsp"/>
